[tools]
# Always include languages first, or wonky things can happen.
# These technically install top to bottom, so if one language relies
# on another, make sure that one is first in the list.
# See: https://mise.jdx.dev/configuration.html#tool-versions
nodejs = '24.12.0'
python = '3.10.13'
java = 'zulu-17.54.21'
ruby = '3.3.6'
bun = '1.2.17'
golang = "1.20.2"
rust = "stable"

# Tools
actionlint = '1.7.7'
awscli = '2.15.44'
cloudflared = "2025.11.1"
coreutils = "0.5.0"
gdu = "5.31.0"
gh = "2.76.2" # should match version in .github/actions/prepare-self-hosted-runner/action.yml
gomigrate = "4.15.1"
hurl = "6.1.1"
jq = "1.8.1" # should match version in .github/actions/prepare-self-hosted-runner/action.yml
ktlint = '1.2.1'
shellcheck = '0.10.0'
yq = "4.47.1" # should match version in .github/actions/prepare-self-hosted-runner/action.yml

# Gems
'gem:cocoapods' = '1.16.2'
'gem:fastlane' = '2.227.2'

# Personal
bashly = "1.3.6"
cargo-binstall = "1.16.7"
just = "1.46.0"
lazygit = "0.58.1"
neovim = "0.11.5"
ripgrep = "15.1.0"
tree-sitter = "0.26.3"
zellij = "0.43.1"
zoxide = "0.9.8"
