[env]
WINIT_HIDPI_FACTOR = "1"

[general]
import = [
  "~/.config/alacritty/themes/themes/hyper.toml"
]

[font]
size = 14.0
[font.normal]
family = "MesloLGS NF"
style = "Regular"
[font.bold]
family = "MesloLGS NF"
style = "Bold"
[font.italic]
family = "MesloLGS NF"
style = "Italic"

[window]
decorations = "Transparent"
opacity = 0.9
blur = true
startup_mode = "Maximized"
title = "Terminal"
decorations_theme_variant = "Dark"
[window.padding]
x = 30
y = 30

[cursor]
[cursor.style]
shape = "Block"
