vars:
  web_path: '/Users/EFrost/code/rocketmoney/packages/web'

cmds:
  web: 'cd {{ web_path }}'
  start_queue: 'node -r @swc-node/register src/scripts/queueWatcher --name {{ queue }} --path ./src/server/jobs/{{ queue }}.ts'

bookmarks:
  - name: renormalization-queue
    desc: Start the web server renormalization queue worker
    cmds:
      - cmd::web
      - cmd::start_queue
    exec: true
    vars:
      queue: 'renormalizeAllSQS'
